#!name=reject规则
#!desc=



# https://github.com/cjx82630/cjxlist

[Rule]
RULE-SET,https://raw.githubusercontent.com/shangguanhongxin/for-surge/master/ini/club-reject.list,REJECT

RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising.list,REJECT
DOMAIN-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising_Domain.list,REJECT

DOMAIN-SET,https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/adaway.txt,REJECT
DOMAIN-SET,https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/annoyances-filter.txt,REJECT
DOMAIN-SET,https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/base-filter.txt,REJECT
DOMAIN-SET,https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/dns-filter.txt,REJECT
DOMAIN-SET,https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/chinese-filter.txt,REJECT
DOMAIN-SET,https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/neohosts-full.txt,REJECT
DOMAIN-SET,https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/neohosts.txt,REJECT
DOMAIN-SET,https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/social-media-filter.txt,REJECT
DOMAIN-SET,https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/tracking-protection-filter.txt,REJECT

DOMAIN-SET,https://raw.githubusercontent.com/easylist/easylistchina/master/easylistchina.txt,REJECT
DOMAIN-SET,https://easylist-downloads.adblockplus.org/easylist.txt,REJECT





DOMAIN-SUFFIX,overseas.weico.cc,REJECT
DOMAIN-SUFFIX,umsns.com,REJECT

URL-REGEX, ^https?://iadmusicmat.music.126.net/.+.jpg,reject
URL-REGEX, ^http://interface.music.163.com/eapi/ad/config/get,reject
URL-REGEX, ^https?://m.ads.8le8le.com/adShow,reject
URL-REGEX, ^https://*.music.126.net/*.jpeg,reject
URL-REGEX,^https:\/\/*\.music\.126\.net\/obj\/*\.jpeg$,REJECT 

[MITM]
hostname = %APPEND% static.zhihu.com,m.ads.8le8le.com,iadmusicmat.music.com,*.music.126.net
